# These projecs were mostly fount at:
# https://kitspace.org/
# https://www.kicad.org/made-with-kicad/

git clone https://github.com/OLIMEX/OLINUXINO OLIMEX--OLINUXINO
git clone https://github.com/AnaviTechnology/anavi-flex AnaviTechnology--anavi-flex
git clone https://github.com/AnaviTechnology/anavi-infrared AnaviTechnology--anavi-infrared
git clone https://github.com/AnaviTechnology/anavi-light-controller AnaviTechnology/anavi-light-controller
git clone https://github.com/AnaviTechnology/anavi-light AnaviTechnology--anavi-light
git clone https://github.com/AntonioMR/ATMEGA328-Motor-Board AntonioMR--ATMEGA328-Motor-Board
git clone https://github.com/mrkindustries/bldc mrkindustries--bldc
git clone https://github.com/mrkindustries/openPSU mrkindustries--openPSU
git clone https://github.com/mrkindustries/BoardA3P mrkindustries--BoardA3P
git clone https://github.com/ciaa/Hardware ciaa--Hardware
git clone https://github.com/bitcraze/crazyflie2-exp-template-electronics bitcraze--crazyflie2-exp-template-electronics
git clone https://github.com/bitcraze/crazyflie-electronics bitcraze--crazyflie-electronics
git clone https://github.com/jpralves/cseduino jpralves--cseduino
git clone https://github.com/weirdgyn/Driverino-Shield weirdgyn--Driverino-Shield
git clone https://github.com/morgulbrut/LoRa32_Node morgulbrut--LoRa32_Node
git clone https://gitlab.com/pierros/astrohat pierros--astrohat
git clone https://github.com/nerdyscout/NodeMCU nerdyscout--NodeMCU
git clone https://github.com/Tyler-Ward/stacklight-hardware Tyler-Ward--stacklight-hardware
git clone https://github.com/descampsa/DynamixelShield descampsa--DynamixelShield
git clone https://github.com/gregdavill/d20-hardware gregdavill--d20-hardware
git clone https://github.com/BeeHive-org/BeeHive BeeHive-org--BeeHive
git clone https://github.com/Jan--Henrik/OtterPill Jan--Henrik--OtterPill
git clone https://github.com/Jan--Henrik/Otter-Iron Jan--Henrik--Otter-Iron
git clone https://github.com/Ottercast/OtterCastAudioV2 Ottercast--OtterCastAudioV2
git clone https://github.com/Jan--Henrik/EF-S-Adapter Jan--Henrik--EF-S-Adapter
git clone https://github.com/Jan--Henrik/Enlightened-Otter Jan--Henrik--Enlightened-Otter
git clone https://github.com/Jan--Henrik/OtterPill-CAN-Adapter Jan--Henrik--OtterPill-CAN-Adapter
git clone https://github.com/Jan--Henrik/ESP-TC-PROG Jan--Henrik--ESP-TC-PROG
git clone https://github.com/GlasgowEmbedded/glasgow GlasgowEmbedded--glasgow
git clone https://github.com/Jan--Henrik/otter-printer Jan--Henrik--otter-printer
git clone https://github.com/kitspace-forks/HACK kitspace-forks--HACK
git clone https://github.com/nasa-jpl/open-source-rover nasa-jpl--open-source-rover
git clone https://github.com/kimitobo/Neocococat kimitobo--Neocococat
git clone https://github.com/intergalaktik/firefly intergalaktik--firefly
git clone https://github.com/Sussex-Neuroscience/voltage-amplifier Sussex-Neuroscience--voltage-amplifier
git clone https://github.com/BadenLab/Openspritzer BadenLab--Openspritzer
git clone https://github.com/Neotron-Compute/Neotron-32-Hardware Neotron-Compute--Neotron-32-Hardware
git clone https://github.com/Jan--Henrik/hoverboard-breakout Jan--Henrik--hoverboard-breakout
git clone https://github.com/amchagas/Flypi amchagas--Flypi
git clone https://github.com/mattvenn/teensy-audio-fx mattvenn--teensy-audio-fx
git clone https://gitlab.com/bath_open_instrumentation_group/sangaboard bath_open_instrumentation_group--sangaboard
git clone https://github.com/less-smog/hardware less-smog--hardware
git clone https://github.com/jonasblixt/blixten jonasblixt--blixten
git clone https://github.com/antevens/boatcontrol antevens--boatcontrol
git clone https://github.com/pms67/HadesFCS pms67--HadesFCS
git clone https://github.com/pluggee/R1000AX pluggee--R1000AX
git clone https://github.com/limpkin/mooltipass limpkin--mooltipass
git clone https://github.com/dmitrystu/nuco-v dmitrystu--nuco-v
git clone https://github.com/Open-Smartwatch/open-smartwatch-gps Open-Smartwatch--open-smartwatch-gps
git clone https://github.com/rusefi/rusefi rusefi--rusefi
git clone https://gitlab.com/scopefun/scopefun-hardware scopefun--scopefun-hardware
git clone https://github.com/OLIMEX/DIY-LAPTOP OLIMEX--DIY-LAPTOP
git clone https://github.com/dm2lct/tlnixie dm2lct--tlnixie
git clone https://github.com/greatscottgadgets/ubertooth greatscottgadgets--ubertooth
 
